// Comprehensive registry of disposable, temporary, burner, and throwaway email services
export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  // Popular Temp Mail Services & Variants
  "playboot.com",
  "mailinator.com",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempmailo.com",
  "tempail.com",
  "guerrillamail.com",
  "guerrillamail.block",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "pokemail.net",
  "spam4.me",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemail.de",
  "20minutemail.com",
  "throwawaymail.com",
  "throwawayemailaddress.com",
  "getairmail.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "cool.fr.nf",
  "jetable.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "fakemailgenerator.com",
  "fakemail.net",
  "fakemail.org",
  "emailfake.com",
  "fakeinbox.com",
  "dispostable.com",
  "trashmail.com",
  "trashmail.net",
  "trashmail.me",
  "trashmail.io",
  "trashmail.at",
  "trashmail.ws",
  "maildrop.cc",
  "mailsac.com",
  "mohmal.com",
  "mohmal.im",
  "mohmal.in",
  "moakt.com",
  "moakt.ws",
  "crazymailing.com",
  "inboxbear.com",
  "nada.ltd",
  "getnada.com",
  "dropmail.me",
  "mytemp.email",
  "mytempemail.com",
  "minutemail.com",
  "emailondeck.com",
  "generator.email",
  "burnermail.io",
  "tmpmail.net",
  "tmpmail.org",
  "tmail.com",
  "tmailor.com",
  "disposablemail.com",
  "mailcatch.com",
  "harakirimail.com",
  "inboxkitten.com",
  "gettempmail.com",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "mailnesia.com",
  "eyepaste.com",
  "inboxes.com",
  "inbox.si",
  "luxusmail.org",
  "brefmail.com",
  "incognitomail.org",
  "zillamail.com",
  "byom.de",
  "trashinbox.com",
  "meltmail.com",
  "guerrilla.com",
  "tempinbox.com",
  "guerrillamail.com",
  "throwaway.email",
  "burner.email",
  "anonbox.net",
  "antichef.com",
  "antichef.net",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "yomail.info",
  "zoemail.org",
  "0-mail.com",
  "0815.ru",
  "0clickemail.com",
  "0wnd.net",
  "0wnd.org",
  "10mail.org",
  "10minutemail.co.uk",
  "10minutemail.pro",
  "123-m.com",
  "1pad.de",
  "20mail.it",
  "2prong.com",
  "3d-painting.com",
  "4warding.com",
  "4warding.net",
  "4warding.org",
  "60minutemail.com",
  "675hosting.com",
  "675hosting.net",
  "675hosting.org",
  "6url.com",
  "754g.com",
  "7tags.com",
  "9ox.net",
  "a-bc.net",
  "afrobacon.com",
  "ajaxapp.net",
  "amileweb.com",
  "amiri.net",
  "anonmails.de",
  "anonymbox.com",
  "anyalias.com",
  "binkmail.com",
  "bio-muesli.net",
  "bobmail.info",
  "bodhi.lawlita.com",
  "bofthew.com",
  "bootybay.de",
  "boun.cr",
  "bouncr.com",
  "breakthru.com",
  "bsnow.net",
  "bugmenot.com",
  "bupkis.org",
  "burntmail.com",
  "cachedot.net",
  "cashette.com",
  "centermail.com",
  "centermail.net",
  "chogmail.com",
  "chongsoft.org",
  "clickmail.info",
  "clrmail.com",
  "cmail.club",
  "cmail.com",
  "cobae.com",
  "cosmorph.com",
  "courrieltemporaire.com",
  "cubiclink.com",
  "curryrasen.de",
  "cust.in",
  "dafd.net",
  "deadaddress.com",
  "deadfake.com",
  "deadletter.org",
  "deaddrop.org",
  "despam.it",
  "devnullmail.com",
  "dfgh.net",
  "dandikmail.com"
]);

/**
 * Checks if the given email is from a known temporary / disposable email service.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes("@")) return false;
  const parts = email.trim().toLowerCase().split("@");
  if (parts.length !== 2) return false;
  
  const domain = parts[1].trim();
  
  // 1. Direct Set lookup (O(1))
  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) {
    return true;
  }

  // 2. Subdomain check (e.g. mail.playboot.com, sub.mailinator.com)
  for (const disposable of DISPOSABLE_EMAIL_DOMAINS) {
    if (domain.endsWith(`.${disposable}`)) {
      return true;
    }
  }

  // 3. Catch generic disposable / burner patterns in domain name
  const suspiciousKeywords = [
    "tempmail",
    "temp-mail",
    "disposable",
    "fakemail",
    "trashmail",
    "throwaway",
    "burnermail",
    "10minute",
    "guerrilla",
    "mohmal",
    "sharklaser",
    "yopmail",
    "maildrop",
    "mailinator",
    "dropmail",
    "dispostable",
    "fakeinbox",
    "nada.ltd",
    "getnada",
    "inboxbear",
    "playboot",
    "spambog",
    "discardmail",
    "tempail",
    "tempinbox"
  ];

  for (const kw of suspiciousKeywords) {
    if (domain.includes(kw)) {
      return true;
    }
  }

  return false;
}
